[run]
init_cmds = [
  ["mage", "-v", "Trace"],
]
watch_all = true
follow_symlinks = true
watch_dirs = [
  "$WORKDIR/pkg",
]
watch_exts = [".go"]
build_delay = 1500
cmds = [
  ["mage", "-v", "Trace"],
]
